#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors touchSensor          = (tSensors) S1;
const tSensors sonarSensor          = (tSensors) S4;

void straight (void);
void left (void);
void straight_son(void);

task main()
{
	straight();
	straight();
	motor[motorB]=100;
	motor[motorC]=100;
	wait1Msec (1000);
}
void straight()
{
		nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;
		nMotorPIDSpeedCtrl[motorC] = mtrSpeedReg;

  	while(SensorValue(touchSensor) == 0)   //a while loop is declared with the touchsensor's value being 0 as it true condition
   	{
      	motor[motorB] = 100;
      	motor[motorC] = 100;

		}
			motor[motorB] = 80;
  		motor[motorC] = 80;
 			wait1Msec(1000);
}
